/**
 * AUTO-GENERATED by eyelevel-design-standards/scripts/generate-mirrors.mjs
 * Source of truth: eyelevel-design-standards/tokens.json
 *
 * DO NOT EDIT THIS FILE BY HAND. Re-run the generator instead:
 *   cd eyelevel-design-standards && node scripts/generate-mirrors.mjs
 *
 * Hand-written chrome tokens (drawerWidth, NAV_ICON_GREY, etc.) live in
 * constants.chrome.ts. The barrel constants.ts re-exports both.
 */

// ────────────────────────────────────────────────────────────────────────
// Colors — brand palette
// ────────────────────────────────────────────────────────────────────────

/** Primary dark. Headings, links, dark surfaces, strong borders. Not true black. */
export const NAVY = "#29335c";
/** Primary CTA + accent. Submit buttons, success chips, eyebrows on navy. */
export const GREEN = "#a1ec83";
/** Secondary accent. Icon-button bg, tag bg, cyan card fill. */
export const CYAN = "#c1e8ee";
/** Quiet section bg. Pale cyan wash, callouts, tint cards. */
export const TINT = "#eff9fb";
/** Label / highlight accent. Section eyebrows, pull-quote highlights. NOT the primary CTA. */
export const CORAL = "#f3663f";
/** Default body color. Slightly-warmer navy. */
export const BODY_TEXT = "#40496b";
/** Alt section bg, input field fill. */
export const GRAY = "#f2f4f5";
/** Surface fill. Cards, inputs, table cells, modal panels. */
export const WHITE = "#ffffff";
/** Default hairline. Navy at 10%. */
export const BORDER = "rgba(41, 51, 92, 0.1)";

// ────────────────────────────────────────────────────────────────────────
// Colors — support palette
// ────────────────────────────────────────────────────────────────────────

/** Destructive / failure. */
export const ERROR_RED = "#f70d1a";
/** Soft warning. */
export const LIGHTER_RED = "#ff7f7f";
/** Inline link accent. Rare. */
export const BLUE = "#0b99ff";
/** Inactive chrome. Slide numbers, timestamps. */
export const DARK_GREY = "#81879a";

// ────────────────────────────────────────────────────────────────────────
// Colors — surface-aware aliases (tokens.md §1.3)
// ────────────────────────────────────────────────────────────────────────

export const EYEBROW_ON_LIGHT = "#f3663f";
export const EYEBROW_ON_DARK = "#a1ec83";
export const BODY_ON_LIGHT = "#40496b";
export const BODY_ON_DARK = "rgba(255, 255, 255, 0.82)";
export const MUTED_ON_LIGHT = "rgba(64, 73, 107, 0.7)";
export const MUTED_ON_DARK = "rgba(255, 255, 255, 0.65)";
/** Input / form field border — navy at 20%. Heavier than the default hairline border (0.1) to define the field's bounds. Use on text inputs, selects, and textareas; not on cards or dividers. */
export const INPUT_BORDER = "rgba(41, 51, 92, 0.2)";
/** Form focus ring shadow — green at 25%. Pair with border-color: var(--gx-green) for the full focus state: border 1px solid green + box-shadow 0 0 0 3px focusRing. */
export const FOCUS_RING = "rgba(161, 236, 131, 0.25)";

// ────────────────────────────────────────────────────────────────────────
// Typography — family & features
// ────────────────────────────────────────────────────────────────────────

/** Product / dashboard / slides / email surface font. Served from Google Fonts; no self-hosting. */
export const FONT_FAMILY = "\"Inter\", system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif";
/** Marketing / Webflow surface font. Served from Fontshare (api.fontshare.com/v2/css?f[]=thicccboi@400,600,700,800&display=swap); no self-hosting. Do not use in product or dashboard surfaces. */
export const FONT_FAMILY_MARKETING = "'Thicccboi', sans-serif";
/** Single-story a (ss01), straight-leg R (cv11), tailed l (cv01). Applied on body. */
export const FONT_FEATURE_SETTINGS = "\"ss01\", \"cv11\", \"cv01\"";

// ────────────────────────────────────────────────────────────────────────
// Typography — weight ladder
// ────────────────────────────────────────────────────────────────────────

/** Body copy, subheads, most UI text. */
export const FONT_WEIGHT_BODY = 400;
/** Labels, eyebrows, CTAs, table headers. */
export const FONT_WEIGHT_LABEL = 600;
/** Headlines, emphasized inline words. */
export const FONT_WEIGHT_HEADLINE = 700;
/** Cover-slide headlines, display-stat numerals. */
export const FONT_WEIGHT_DISPLAY = 800;

// ────────────────────────────────────────────────────────────────────────
// Typography — letter spacing
// ────────────────────────────────────────────────────────────────────────

/** Uppercase eyebrows and overline labels. */
export const LETTER_SPACING_LABEL = "0.12em";
/** Button labels (tighter than eyebrows). */
export const LETTER_SPACING_BUTTON = "0.04em";
/** Pill / chip chrome — MuiChip, GxPill, button-internal labels. */
export const LETTER_SPACING_CHIP = "0.5px";
/** Display-heading optical tracking (negative). */
export const LETTER_SPACING_DISPLAY_TIGHT = "-0.01em";
/** Page-heading optical tracking. */
export const LETTER_SPACING_HEADING_TIGHT = "-0.005em";
/** Slide pill and CTA label tracking — tighter than the eyebrow but wider than button. Slide-only; web uses --gx-track-button. */
export const LETTER_SPACING_PILL = "0.08em";
/** Display-stat and cover-context label tracking — wide tracking at small sizes on the large slide canvas. */
export const LETTER_SPACING_DISPLAY_LABEL = "0.14em";

// ────────────────────────────────────────────────────────────────────────
// Typography — line height
// ────────────────────────────────────────────────────────────────────────

/** Cover / display headings. */
export const LINE_HEIGHT_DISPLAY = 1.1;
/** Page headings. */
export const LINE_HEIGHT_HEADING = 1.15;
/** Section headings. */
export const LINE_HEIGHT_SECTION = 1.2;
/** Subsection headings. */
export const LINE_HEIGHT_SUBSECTION = 1.25;
/** Card headings. */
export const LINE_HEIGHT_CARD_HEADING = 1.3;
/** Card subheads. */
export const LINE_HEIGHT_CARD_SUBHEAD = 1.4;
/** Body-sm / caption. */
export const LINE_HEIGHT_TIGHT_BODY = 1.5;
/** Default body (web is looser than slides). */
export const LINE_HEIGHT_BODY = 1.6;

// ────────────────────────────────────────────────────────────────────────
// Web size scale
// ────────────────────────────────────────────────────────────────────────

/** Marketing hero / cover display heading. Weight 800. Webflow/marketing surfaces only — not used in the product dashboard. (64px) */
export const FONT_SIZE_DISPLAY_LG = "4rem";
/** Marketing display sub-heading. Weight 700. Webflow/marketing surfaces only. (54px) */
export const FONT_SIZE_DISPLAY_MD = "3.375rem";
/** Display heading (hero, cover). Weight 700. (40px) */
export const FONT_SIZE_H1 = "2.5rem";
/** Page heading. Weight 700. (32px) */
export const FONT_SIZE_H2 = "2rem";
/** Section heading. Weight 700. (26px) */
export const FONT_SIZE_H3 = "1.625rem";
/** Subsection. Weight 700. (22px) */
export const FONT_SIZE_H4 = "1.375rem";
/** Card heading. Weight 700. (18px) */
export const FONT_SIZE_H5 = "1.125rem";
/** Card subhead. Weight 700. (16px) */
export const FONT_SIZE_H6 = "1rem";
/** Default body. Weight 400. (16px) */
export const FONT_SIZE_BODY = "1rem";
/** Secondary paragraphs, table rows. (14px) */
export const FONT_SIZE_BODY_SM = "0.875rem";
/** Metadata / timestamps / captions. (13px) */
export const FONT_SIZE_CAPTION = "0.8125rem";
/** Uppercase eyebrows, overline labels. (12px) */
export const FONT_SIZE_LABEL = "0.75rem";
/** Dense inline pill chrome (GxPill dense mode). (11px) */
export const FONT_SIZE_LABEL_DENSE = "0.7rem";

// ────────────────────────────────────────────────────────────────────────
// Border radii (webflow scale)
// ────────────────────────────────────────────────────────────────────────

/** Tight inner shapes — hairline divider wraps, inline chips. */
export const BORDER_RADIUS_SM = "4px";
/** Inner / nested surfaces, inputs. */
export const BORDER_RADIUS = "6px";
/** Dropdown menus, toast, medium-surface containers. */
export const BORDER_RADIUS_2X = "12px";
/** Top-level cards, accordions. The default unless a reason not to. */
export const BORDER_RADIUS_CARD = "20px";
/** Buttons, pills, tags, segmented button ends. Full-pill shape. */
export const BORDER_RADIUS_PILL = "200px";

// ────────────────────────────────────────────────────────────────────────
// Spacing (MUI units, 1 = 8px)
// ────────────────────────────────────────────────────────────────────────

/** Default inner padding on GxCard and most surfaces. 16px. */
export const PADDING = 2;
/** Outer padding on the main content pane (desktop). 40px. */
export const MAIN_CONTENT_PADDING = 5;
/** Top margin on main content to clear the fixed AppBar. 56px. */
export const MAIN_CONTENT_TOP_MARGIN = 7;

// ────────────────────────────────────────────────────────────────────────
// Durations
// ────────────────────────────────────────────────────────────────────────

/** Auto-dismiss ms for toast / message bar. */
export const MESSAGE_BAR_DURATION = 20000;

// ────────────────────────────────────────────────────────────────────────
// Breakpoints (px thresholds). md=900 (MUI default) is the
// iPad-portrait-to-landscape divide and the threshold above which the
// onboarding step strip fits on one row. Below 900: compact strip + 1-up
// cards (phones + iPad portrait). At/above 900: full strip + 3-up cards
// (iPad landscape, laptops, desktops).
// ────────────────────────────────────────────────────────────────────────

export const BREAKPOINT_XS = 0;
export const BREAKPOINT_SM = 600;
/** MUI default. iPad-portrait-to-landscape divide; full step strip fits above this. */
export const BREAKPOINT_MD = 900;
export const BREAKPOINT_LG = 1200;
export const BREAKPOINT_XL = 1536;

// ────────────────────────────────────────────────────────────────────────
// Webflow/marketing spacing scale (raw px, not MUI units)
// ────────────────────────────────────────────────────────────────────────

/** --space-2 · micro gaps (icon pairs, tight inline spacing). */
export const SPACING_WEBFLOW_SPACE_2 = "7px";
/** --space-3 · tight pairs (label-to-input, sibling elements). */
export const SPACING_WEBFLOW_SPACE_3 = "14px";
/** --space-4 · form fields (input vertical padding, control groups). */
export const SPACING_WEBFLOW_SPACE_4 = "20px";
/** --space-5 · card padding (inner card content area). */
export const SPACING_WEBFLOW_SPACE_5 = "24px";
/** --space-6 · section padding-x, standard column gap. */
export const SPACING_WEBFLOW_SPACE_6 = "28px";
/** --space-8 · large button padding, tight section internal gaps. */
export const SPACING_WEBFLOW_SPACE_8 = "36px";
/** --space-10 · section header margin-bottom. */
export const SPACING_WEBFLOW_SPACE_10 = "56px";
/** --space-12 · reduced section padding (compact pages). */
export const SPACING_WEBFLOW_SPACE_12 = "84px";
/** --space-16 · full section padding, top and bottom. */
export const SPACING_WEBFLOW_SPACE_16 = "112px";
